-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfcFh5JFbWS7SkTnD
Uu1fWVDD9UT5j6OIH4NV+6sl7xegCgYIKoZIzj0DAQehRANCAATm8fOj3TbnrQwj
q/5EA+IuQ2hj+1Yj5Ri/UiQCX1hlfesxz87KwAmnA1/tHcwprBxQTwL/QvcGaCLy
rxyTs+SM
-----END PRIVATE KEY-----